# START: docker-compose up -d
# STOP: docker-compose down
version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: meu-mongo-local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db

  weather-api:
    build:
      context: ./data_processing
      dockerfile: Dockerfile
    container_name: weather-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production

volumes:
  mongo_data:
